---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-react-app
  labels:
    app: simple-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple-react-app
  template:
    metadata:
      labels:
        app: simple-react-app
    spec:
      containers:
      - name: simple-react-app
        image: gastonkanze/react-app
        ports:
        - containerPort: 3000 
---
apiVersion: v1
kind: Service
metadata:
  name: simple-react-app
spec:
  selector:
    app: simple-react-app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30000
  type: NodePort